# 딥 러닝을 이용한 자연어 처리 입문

아래 링크의 E-book을 보고 실습한 내용입니다.

WikiDocs 주소: https://wikidocs.net/31766


# 2장 텍스트 전처리

## 9절 Splitting data

## Splitting data

지도 학습을 진행할 때 보통 데이터 셋을 아래와 같이 훈련, 검증, 테스트 세 개로 나눈다.

- 훈련 데이터 셋: 학습지, 문제지 (ex. 빨간펜, 쎈 수학)
- 검증 데이터 셋: 기출 문제 (실제 시험과는 다름)
- 테스트 데이터 셋: 실제 시험 (훈련 과정 동안 단 한 번도 보지 못한 데이터 ex. 수능)

보통 아래와 같은 비율로 나눈다.

- 훈련 : 검증 : 테스트 = 2 : 2 : 6 

In [14]:
# 예제 데이터 생성

import numpy as np
from sklearn.model_selection import train_test_split

X, y = np.arange(10).reshape((5, 2)), range(5)

4.0

### X, Y 분리하기

In [23]:
# zip 함수 활용
data = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*data)
print(X)
print(y)
print()

# numpy 사용
import numpy as np
data = np.arange(0,16).reshape((4,4))
print("data:", data, "\n")

X=data[:, :3]
y=data[:,3]
print("X:", X)
print("y:", y)

('a', 'b', 'c')
(1, 2, 3)

data: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

X: [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y: [ 3  7 11 15]


### Scikit-learn으로 테스트 데이터 분할

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)

X_train: [[2 3]
 [8 9]
 [0 1]
 [6 7]]
X_test: [[4 5]]
y_train: [1, 4, 0, 3]
y_test: [2]


### numpy로 테스트 데이터 분할

In [15]:
train_ratio = 0.8

X_train = X[:int(len(X)*train_ratio)]
y_train = y[:int(len(y)*train_ratio)]

X_test = X[int(len(X)*train_ratio):]
y_test = y[int(len(y)*train_ratio):]

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)

X_train: [[0 1]
 [2 3]
 [4 5]
 [6 7]]
X_test: [[8 9]]
y_train: range(0, 4)
y_test: range(4, 5)
